baseurl = "http://rjpilot.netlify.com"
languageCode = "en-us"
title = "Experiments for the R Journal"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/RJexpts/pilot"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Di Cook](https://dicook.org) 2017-9"

    # path to the favicon, under "static"
    favicon = "img/logo.png"

    [params.logo]
    url = "/logo.png"
    width = 50
    height = 50
    alt = "Logo"

