baseurl = "http://rjpilot.netlify.com"
languageCode = "en-us"
title = "Experiments for the R Journal"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "https://rjpilot.netlify.app"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/RJexpts/pilot"
[[menu.main]]
    name = "R Journal"
    url = "https://journal.r-project.org"

[params]
    description = "A website built through Hugo and blogdown."
    title = "Experiments for the R Journal"
    footer = "&copy; Di Cook with a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/)"

    # path to the favicon, under "static"
    favicon = "img/logo.png"

    [params.logo]
    url = "/logo.png"
    width = 50
    height = 50
    alt = "Logo"

